version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      updates:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
