version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  build:
    executor: &execWithGo
      name: go/default
      tag: "1.13"
    steps:
      - checkout
      - go/load-cache
      - go/test
      - go/save-cache

  release:
    executor: *execWithGo
    steps:
      - checkout
      - go/load-cache
      - run:
          name: goreleaser
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/